theme: minima
title: Publishing with Jekyll
author: Herrenrod
email: herrenrod@herrenhub.com
description: > # this means to ignore newlines until "baseurl:"
  I am a budding software developer currently working on JavaScript, CSS and HTML.
  You are welcome to explore my portfolio <a href="">here.</a>
# social links
twitter_username: nestherrod # DO NOT include the @ character, or else the build will fail!
github_username:  herrenrod # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
